var hierarchy =
[
    [ "VieVS::AstronomicalParameters", "class_vie_v_s_1_1_astronomical_parameters.html", null ],
    [ "VieVS::CalibratorBlock", "class_vie_v_s_1_1_calibrator_block.html", null ],
    [ "VieVS::Source::Event", "struct_vie_v_s_1_1_source_1_1_event.html", null ],
    [ "VieVS::Station::Event", "struct_vie_v_s_1_1_station_1_1_event.html", null ],
    [ "VieVS::Baseline::Event", "struct_vie_v_s_1_1_baseline_1_1_event.html", null ],
    [ "VieVS::Flags", "class_vie_v_s_1_1_flags.html", null ],
    [ "iauASTROM", "structiau_a_s_t_r_o_m.html", null ],
    [ "iauLDBODY", "structiau_l_d_b_o_d_y.html", null ],
    [ "VieVS::LogParser::LogScan", "struct_vie_v_s_1_1_log_parser_1_1_log_scan.html", null ],
    [ "VieVS::LookupTable", "class_vie_v_s_1_1_lookup_table.html", null ],
    [ "VieVS::ObservationMode", "class_vie_v_s_1_1_observation_mode.html", null ],
    [ "VieVS::Source::Optimization", "struct_vie_v_s_1_1_source_1_1_optimization.html", null ],
    [ "VieVS::ParameterGroup", "class_vie_v_s_1_1_parameter_group.html", null ],
    [ "VieVS::MultiScheduling::Parameters", "struct_vie_v_s_1_1_multi_scheduling_1_1_parameters.html", null ],
    [ "VieVS::Initializer::Parameters", "struct_vie_v_s_1_1_initializer_1_1_parameters.html", null ],
    [ "VieVS::Scheduler::Parameters", "struct_vie_v_s_1_1_scheduler_1_1_parameters.html", null ],
    [ "VieVS::ParameterSettings::ParametersBaselines", "struct_vie_v_s_1_1_parameter_settings_1_1_parameters_baselines.html", null ],
    [ "VieVS::ParameterSettings", "class_vie_v_s_1_1_parameter_settings.html", null ],
    [ "VieVS::ParameterSetup", "class_vie_v_s_1_1_parameter_setup.html", null ],
    [ "VieVS::ParameterSettings::ParametersSources", "struct_vie_v_s_1_1_parameter_settings_1_1_parameters_sources.html", null ],
    [ "VieVS::ParameterSettings::ParametersStations", "struct_vie_v_s_1_1_parameter_settings_1_1_parameters_stations.html", null ],
    [ "VieVS::Initializer::PRECALC", "struct_vie_v_s_1_1_initializer_1_1_p_r_e_c_a_l_c.html", null ],
    [ "VieVS::Source::PreCalculated", "struct_vie_v_s_1_1_source_1_1_pre_calculated.html", null ],
    [ "VieVS::Scheduler::PreCalculated", "struct_vie_v_s_1_1_scheduler_1_1_pre_calculated.html", null ],
    [ "VieVS::Scan::ScanSequence", "struct_vie_v_s_1_1_scan_1_1_scan_sequence.html", null ],
    [ "VieVS::Baseline::Statistics", "struct_vie_v_s_1_1_baseline_1_1_statistics.html", null ],
    [ "VieVS::Source::Statistics", "struct_vie_v_s_1_1_source_1_1_statistics.html", null ],
    [ "VieVS::Station::Statistics", "struct_vie_v_s_1_1_station_1_1_statistics.html", null ],
    [ "VieVS::Subnetting", "struct_vie_v_s_1_1_subnetting.html", null ],
    [ "VieVS::TimeSystem", "class_vie_v_s_1_1_time_system.html", null ],
    [ "VieVS::VieSchedpp", "class_vie_v_s_1_1_vie_schedpp.html", null ],
    [ "VieVS::VieVS_Object", "class_vie_v_s_1_1_vie_v_s___object.html", [
      [ "VieVS::AbstractAntenna", "class_vie_v_s_1_1_abstract_antenna.html", [
        [ "VieVS::Antenna_AzEl", "class_vie_v_s_1_1_antenna___az_el.html", null ],
        [ "VieVS::Antenna_HaDc", "class_vie_v_s_1_1_antenna___ha_dc.html", null ],
        [ "VieVS::Antenna_XYew", "class_vie_v_s_1_1_antenna___x_yew.html", null ]
      ] ],
      [ "VieVS::AbstractCableWrap", "class_vie_v_s_1_1_abstract_cable_wrap.html", [
        [ "VieVS::CableWrap_AzEl", "class_vie_v_s_1_1_cable_wrap___az_el.html", null ],
        [ "VieVS::CableWrap_HaDc", "class_vie_v_s_1_1_cable_wrap___ha_dc.html", null ],
        [ "VieVS::CableWrap_XYew", "class_vie_v_s_1_1_cable_wrap___x_yew.html", null ]
      ] ],
      [ "VieVS::AbstractFlux", "class_vie_v_s_1_1_abstract_flux.html", [
        [ "VieVS::Flux_B", "class_vie_v_s_1_1_flux___b.html", null ],
        [ "VieVS::Flux_M", "class_vie_v_s_1_1_flux___m.html", null ]
      ] ],
      [ "VieVS::AbstractHorizonMask", "class_vie_v_s_1_1_abstract_horizon_mask.html", [
        [ "VieVS::HorizonMask_line", "class_vie_v_s_1_1_horizon_mask__line.html", null ],
        [ "VieVS::HorizonMask_step", "class_vie_v_s_1_1_horizon_mask__step.html", null ]
      ] ],
      [ "VieVS::Equipment", "class_vie_v_s_1_1_equipment.html", [
        [ "VieVS::Equipment_elDependent", "class_vie_v_s_1_1_equipment__el_dependent.html", null ]
      ] ],
      [ "VieVS::HighImpactScanDescriptor", "class_vie_v_s_1_1_high_impact_scan_descriptor.html", null ],
      [ "VieVS::HighImpactScanDescriptor::AzElDescriptor", "class_vie_v_s_1_1_high_impact_scan_descriptor_1_1_az_el_descriptor.html", null ],
      [ "VieVS::Initializer", "class_vie_v_s_1_1_initializer.html", null ],
      [ "VieVS::LogParser", "class_vie_v_s_1_1_log_parser.html", null ],
      [ "VieVS::MultiScheduling", "class_vie_v_s_1_1_multi_scheduling.html", null ],
      [ "VieVS::Network", "class_vie_v_s_1_1_network.html", null ],
      [ "VieVS::Observation", "class_vie_v_s_1_1_observation.html", null ],
      [ "VieVS::PointingVector", "class_vie_v_s_1_1_pointing_vector.html", null ],
      [ "VieVS::Position", "class_vie_v_s_1_1_position.html", null ],
      [ "VieVS::Scan", "class_vie_v_s_1_1_scan.html", null ],
      [ "VieVS::ScanTimes", "class_vie_v_s_1_1_scan_times.html", null ],
      [ "VieVS::Skd", "class_vie_v_s_1_1_skd.html", null ],
      [ "VieVS::SkdCatalogReader", "class_vie_v_s_1_1_skd_catalog_reader.html", null ],
      [ "VieVS::SkdParser", "class_vie_v_s_1_1_skd_parser.html", null ],
      [ "VieVS::SkyCoverage", "class_vie_v_s_1_1_sky_coverage.html", null ],
      [ "VieVS::StationEndposition", "class_vie_v_s_1_1_station_endposition.html", null ],
      [ "VieVS::Subcon", "class_vie_v_s_1_1_subcon.html", null ],
      [ "VieVS::Vex", "class_vie_v_s_1_1_vex.html", null ],
      [ "VieVS::VieVS_NamedObject", "class_vie_v_s_1_1_vie_v_s___named_object.html", [
        [ "VieVS::Baseline", "class_vie_v_s_1_1_baseline.html", null ],
        [ "VieVS::Baseline::Parameters", "class_vie_v_s_1_1_baseline_1_1_parameters.html", null ],
        [ "VieVS::Bbc", "class_vie_v_s_1_1_bbc.html", null ],
        [ "VieVS::Bbc::Bbc_assign", "class_vie_v_s_1_1_bbc_1_1_bbc__assign.html", null ],
        [ "VieVS::Freq", "class_vie_v_s_1_1_freq.html", null ],
        [ "VieVS::Freq::Chan_def", "class_vie_v_s_1_1_freq_1_1_chan__def.html", null ],
        [ "VieVS::If", "class_vie_v_s_1_1_if.html", null ],
        [ "VieVS::If::If_def", "class_vie_v_s_1_1_if_1_1_if__def.html", null ],
        [ "VieVS::Mode", "class_vie_v_s_1_1_mode.html", null ],
        [ "VieVS::Output", "class_vie_v_s_1_1_output.html", null ],
        [ "VieVS::Scheduler", "class_vie_v_s_1_1_scheduler.html", null ],
        [ "VieVS::Source", "class_vie_v_s_1_1_source.html", null ],
        [ "VieVS::Source::Parameters", "class_vie_v_s_1_1_source_1_1_parameters.html", null ],
        [ "VieVS::Station", "class_vie_v_s_1_1_station.html", null ],
        [ "VieVS::Station::Parameters", "class_vie_v_s_1_1_station_1_1_parameters.html", null ],
        [ "VieVS::Track", "class_vie_v_s_1_1_track.html", null ],
        [ "VieVS::Track::Fanout_definition", "class_vie_v_s_1_1_track_1_1_fanout__definition.html", null ]
      ] ]
    ] ],
    [ "VieVS::Station::WaitTimes", "struct_vie_v_s_1_1_station_1_1_wait_times.html", null ],
    [ "VieVS::WeightFactors", "class_vie_v_s_1_1_weight_factors.html", null ]
];